# modified from
# https://github.com/muzimuzhi/hello-github-actions/blob/checkout-lfs/.github/workflows/main.yml
name: Checkout Git LFS
on: 
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          git lfs pull --include=asset
      - uses: actions/upload-pages-artifact@v1
        with:
          path: website
